import type { Language } from "./i18n";

const copy = {
  en: { title: "Virtual room users", description: "Place system-generated silent learners in empty fixed rooms. They leave immediately when a real user joins.", enabled: "Enable virtual users", users: "Number of virtual users", rooms: "Number of rooms", hint: "Use 1–4 virtual users per room. Rooms with at least two virtual users exchange messages in the primary language. Custom rooms and rooms with real users are never selected.", save: "Save configuration", saving: "Saving...", saved: "Virtual user configuration updated.", invalid: "Choose at least one user per room and no more than four users per room.", loadFailed: "Virtual user settings could not be loaded.", active: "Active", inactive: "Inactive", virtualUser: "Virtual user" },
  vi: { title: "Người dùng ảo trong phòng", description: "Phân người học im lặng do hệ thống tạo vào các phòng cố định đang trống. Họ rời ngay khi người dùng thật tham gia.", enabled: "Bật người dùng ảo", users: "Số người dùng ảo", rooms: "Số phòng được phân", hint: "Mỗi phòng có từ 1–4 người dùng ảo. Phòng có ít nhất hai người dùng ảo sẽ trò chuyện bằng ngôn ngữ chính. Custom room và phòng có người thật sẽ không được chọn.", save: "Lưu cấu hình", saving: "Đang lưu...", saved: "Đã cập nhật cấu hình người dùng ảo.", invalid: "Mỗi phòng cần ít nhất một và không quá bốn người dùng ảo.", loadFailed: "Không thể tải cấu hình người dùng ảo.", active: "Đang bật", inactive: "Đang tắt", virtualUser: "Người dùng ảo" },
  zh: { title: "虚拟房间用户", description: "将系统生成的安静学习者分配到空的固定房间。真实用户加入时，他们会立即离开。", enabled: "启用虚拟用户", users: "虚拟用户数量", rooms: "分配房间数量", hint: "每个房间安排1–4个虚拟用户。至少有两名虚拟用户的房间会使用主要语言聊天。不会选择自定义房间或已有真实用户的房间。", save: "保存配置", saving: "保存中...", saved: "虚拟用户配置已更新。", invalid: "每个房间至少安排1人，最多4人。", loadFailed: "无法加载虚拟用户设置。", active: "已启用", inactive: "未启用", virtualUser: "虚拟用户" },
  ja: { title: "仮想ルームユーザー", description: "システム生成のサイレント学習者を空いている固定ルームに配置します。実ユーザーが参加すると直ちに退出します。", enabled: "仮想ユーザーを有効化", users: "仮想ユーザー数", rooms: "配置するルーム数", hint: "1ルームあたり1～4人。2人以上の仮想ユーザーがいるルームでは主要言語で会話します。カスタムルームと実ユーザーがいるルームは対象外です。", save: "設定を保存", saving: "保存中...", saved: "仮想ユーザー設定を更新しました。", invalid: "各ルームに1人以上4人以下を設定してください。", loadFailed: "仮想ユーザー設定を読み込めませんでした。", active: "有効", inactive: "無効", virtualUser: "仮想ユーザー" }
} satisfies Record<Language, Record<string, string>>;

export type VirtualUserCopyKey = keyof typeof copy.en;
export const virtualUserTranslate = (language: Language, key: VirtualUserCopyKey) => copy[language][key] ?? copy.en[key];
