import type { Language } from "./i18n";

const copy = {
  en: { share: "Share YouTube", manage: "Manage YouTube video", url: "YouTube URL", placeholder: "Paste a YouTube link or video ID", add: "Share video", replace: "Replace video", remove: "Remove video", cancel: "Cancel", invalid: "Please enter a valid YouTube video URL.", denied: "You do not have permission to manage this video.", failed: "The YouTube video could not be updated. Please try again.", shared: "YouTube video shared.", removed: "YouTube video removed.", show: "Show shared YouTube video", hide: "Hide video and return to the room topic", pause: "Pause video", resume: "Resume video", ownerControls: "Only the room owner can seek or change the video.", recommendations: "Recommended videos", recommendationsForCurrent: "Related to the current video", loadingRecommendations: "Loading YouTube recommendations...", recommendationsUnavailable: "Recommendations are unavailable. You can still paste a YouTube link.", recommendationsNotConfigured: "YouTube recommendations are not configured on the server.", recommendationsQuotaExceeded: "The YouTube recommendation quota has been reached. Try again later.", selectVideo: "Select video", embeddingDisabled: "The video owner does not allow this video to play on other websites.", videoUnavailable: "This video is private, deleted, or unavailable.", playerFailed: "YouTube could not play this video here.", openYouTube: "Open on YouTube" },
  vi: { share: "Chia sẻ YouTube", manage: "Quản lý video YouTube", url: "Đường dẫn YouTube", placeholder: "Dán đường dẫn YouTube hoặc video ID", add: "Chia sẻ video", replace: "Đổi video", remove: "Xóa video", cancel: "Hủy", invalid: "Vui lòng nhập đường dẫn video YouTube hợp lệ.", denied: "Bạn không có quyền quản lý video này.", failed: "Chưa thể cập nhật video YouTube. Vui lòng thử lại.", shared: "Đã chia sẻ video YouTube.", removed: "Đã xóa video YouTube.", show: "Hiển thị video YouTube được chia sẻ", hide: "Ẩn video và quay lại chủ đề phòng", pause: "Tạm dừng video", resume: "Tiếp tục video", ownerControls: "Chỉ chủ phòng có thể tua hoặc thay đổi video.", recommendations: "Video đề xuất", recommendationsForCurrent: "Liên quan đến video đang phát", loadingRecommendations: "Đang tải đề xuất từ YouTube...", recommendationsUnavailable: "Tạm thời không tải được đề xuất. Bạn vẫn có thể dán đường dẫn YouTube.", recommendationsNotConfigured: "Backend chưa được cấu hình API key cho đề xuất YouTube.", recommendationsQuotaExceeded: "Đã hết quota đề xuất của YouTube. Vui lòng thử lại sau.", selectVideo: "Chọn video", embeddingDisabled: "Chủ video không cho phép phát video này trên website khác.", videoUnavailable: "Video này đang riêng tư, đã bị xóa hoặc không khả dụng.", playerFailed: "YouTube không thể phát video này tại đây.", openYouTube: "Mở trên YouTube" },
  zh: { share: "分享 YouTube", manage: "管理 YouTube 视频", url: "YouTube 链接", placeholder: "粘贴 YouTube 链接或视频 ID", add: "分享视频", replace: "更换视频", remove: "删除视频", cancel: "取消", invalid: "请输入有效的 YouTube 视频链接。", denied: "你没有权限管理此视频。", failed: "无法更新 YouTube 视频，请重试。", shared: "YouTube 视频已分享。", removed: "YouTube 视频已删除。", show: "显示共享的 YouTube 视频", hide: "隐藏视频并返回房间主题", pause: "暂停视频", resume: "继续播放", ownerControls: "只有房主可以跳转或更换视频。", recommendations: "推荐视频", recommendationsForCurrent: "与当前视频相关", loadingRecommendations: "正在加载 YouTube 推荐...", recommendationsUnavailable: "暂时无法加载推荐。你仍可粘贴 YouTube 链接。", recommendationsNotConfigured: "服务器尚未配置 YouTube 推荐 API 密钥。", recommendationsQuotaExceeded: "YouTube 推荐配额已用完，请稍后重试。", selectVideo: "选择视频", embeddingDisabled: "视频所有者不允许在其他网站播放此视频。", videoUnavailable: "此视频为私享、已删除或不可用。", playerFailed: "YouTube 无法在此处播放该视频。", openYouTube: "在 YouTube 中打开" },
  ja: { share: "YouTubeを共有", manage: "YouTube動画を管理", url: "YouTube URL", placeholder: "YouTubeリンクまたは動画IDを貼り付け", add: "動画を共有", replace: "動画を変更", remove: "動画を削除", cancel: "キャンセル", invalid: "有効なYouTube動画URLを入力してください。", denied: "この動画を管理する権限がありません。", failed: "YouTube動画を更新できませんでした。もう一度お試しください。", shared: "YouTube動画を共有しました。", removed: "YouTube動画を削除しました。", show: "共有YouTube動画を表示", hide: "動画を閉じてルームトピックに戻る", pause: "一時停止", resume: "再生", ownerControls: "シークや動画変更はルームオーナーのみ可能です。", recommendations: "おすすめ動画", recommendationsForCurrent: "再生中の動画に関連", loadingRecommendations: "YouTubeのおすすめを読み込んでいます...", recommendationsUnavailable: "おすすめを読み込めません。YouTubeリンクは引き続き貼り付けできます。", recommendationsNotConfigured: "サーバーにYouTubeおすすめ用APIキーが設定されていません。", recommendationsQuotaExceeded: "YouTubeおすすめの割り当て上限に達しました。後でもう一度お試しください。", selectVideo: "動画を選択", embeddingDisabled: "動画の所有者が他のサイトでの再生を許可していません。", videoUnavailable: "この動画は非公開、削除済み、または利用できません。", playerFailed: "この場所ではYouTube動画を再生できません。", openYouTube: "YouTubeで開く" }
} satisfies Record<Language, Record<string, string>>;

export type YouTubeCopyKey = keyof typeof copy.en;
export const youtubeTranslate = (language: Language, key: YouTubeCopyKey) => copy[language][key] ?? copy.en[key];
